name: 'Registry CI'
description: 'PDS Registry Integration Tests'

inputs:
  harvest-branch:
    description: 'Git branch of NASA-PDS/harvest repo'
    required: true
    default: 'master'
  manager-branch:
    description: 'Git branch of NASA-PDS/pds-registry-mgr-elastic repo'
    required: true
    default: 'master'
  api-branch:
    description: 'Git branch of NASA-PDS/registry-api-service repo'
    required: true
    default: 'master'

runs:
  using: "composite"
  steps:
    # Build Harvest
    - shell: bash
      run: bash ${{ github.action_path }}/docker/scripts/run_build.sh harvest ${{ inputs.harvest-branch }}

    # Build Registry manager
    - shell: bash
      run: bash ${{ github.action_path }}/docker/scripts/run_build.sh manager ${{ inputs.manager-branch }}

    # Build API Server
    - shell: bash
      run: bash ${{ github.action_path }}/docker/scripts/run_build.sh api ${{ inputs.api-branch }}

    # Start API Server
    - shell: bash
      run: bash ${{ github.action_path }}/docker/scripts/run_api_server.sh ${{ job.container.network }}
