name: 'Registry CI'
description: 'PDS Registry Integration Tests'

inputs:
  harvest-branch:
    description: 'Git branch of NASA-PDS/harvest repo'
    required: true
    default: 'master'
  manager-branch:
    description: 'Git branch of NASA-PDS/pds-registry-mgr-elastic repo'
    required: true
    default: 'master'
  api-branch:
    description: 'Git branch of NASA-PDS/registry-api-service repo'
    required: true
    default: 'master'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: ${{ github.action_path }}/docker/scripts/run_maven.sh harvest ${{ inputs.harvest-branch }}

    - shell: bash
      run: ${{ github.action_path }}/docker/scripts/run_maven.sh manager ${{ inputs.manager-branch }}
