name: 'Registry CI'
description: 'PDS Registry Integration Tests'

inputs:
  harvest-branch:
    description: 'Git branch of NASA-PDS/harvest repo'
    required: true
    default: 'master'
  manager-branch:
    description: 'Git branch of NASA-PDS/pds-registry-mgr-elastic repo'
    required: true
    default: 'master'
  api-branch:
    description: 'Git branch of NASA-PDS/registry-api-service repo'
    required: true
    default: 'master'
  docker-network:
    description: 'Docker network name'
    required: true

runs:
  using: "composite"
  steps:

    - shell: bash
      run: echo Network param: ${{ inputs.docker-network }}

    - shell: bash
      run: echo Network job: ${{ job.container.network }}
