name: 'Registry CI'
description: 'PDS Registry Integration Tests'

inputs:
  harvest-branch:
    description: 'Git branch of NASA-PDS/harvest repo'
    required: true
    default: 'main'
  manager-branch:
    description: 'Git branch of NASA-PDS/pds-registry-mgr-elastic repo'
    required: true
    default: 'main'
  api-branch:
    description: 'Git branch of NASA-PDS/registry-api-service repo'
    required: true
    default: 'main'

runs:
  using: "composite"
  steps:
    - name: Create Docker network
      shell: bash
      run: docker network create registry-ci

    - name: Start Elasticsearch
      shell: bash
      run: bash ${{ github.action_path }}/docker/scripts/run_es.sh registry-ci

    - name: Wait for Elasticsearch to start
      shell: bash
      run: bash ${{ github.action_path }}/docker/scripts/wait_for_http.sh localhost:9200
