name: 'Registry CI'
description: 'PDS Registry Integration Tests'
inputs:
  harvest-branch:
    description: 'Git branch of NASA-PDS/harvest repo'
    required: true
    default: 'master'
  manager-branch:
    description: 'Git branch of NASA-PDS/pds-registry-mgr-elastic repo'
    required: true
    default: 'master'
  api-branch:
    description: 'Git branch of NASA-PDS/registry-api-service repo'
    required: true
    default: 'master'
runs:
  using: "composite"

  services:
    elastic:
      image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
      env:
        discovery.type: single-node
      ports:
        - 9200:9200
      options: >-
        --health-cmd "curl localhost:9200"
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5
  steps:
    - run: echo Harvest ${{ inputs.harvest-branch }}.
      shell: bash
    - run: echo Manager ${{ inputs.manager-branch }}.
      shell: bash
    - run: echo API ${{ inputs.api-branch }}.
      shell: bash
