name: Run CI

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    # Elasticsearch
    services:
      elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
        env:
          discovery.type: single-node
        ports:
          - 9200:9200
        options: >-
          --health-cmd "curl localhost:9200"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Preparing to build
      run: mkdir /tmp/build

    - name: Build Harvest
      run: docker run --rm --name registry-build -v /tmp/build:/build tdddblog/pds_maven_build:1.0 harvest
    - name: Build Registry Manager
      run: docker run --rm --name registry-build -v /tmp/build:/build tdddblog/pds_maven_build:1.0 manager
#    - name: Build API
#      run: docker run --rm --name registry-build -v /tmp/build:/build tdddblog/pds_maven_build:1.0 api

    - name: Load Test Data
      run: >-
        docker run --rm --name registry-load --network ${{ job.container.network }}
        -e "ES_URL=http://elastic:9200" -v /tmp/build:/build tdddblog/pds_load_test_data:1.0
