name: Test Action

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: NASA-PDS/registry-ci@main
        with: 
          harvest-branch: 'bug-130'
          manager-branch: 'main'
          api-branch: 'main'
