name: Test script

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      #run: ${GITHUB_WORKSPACE}/docker/scripts/wait_for_http.sh http://localhost:9200
      - run: "cat ${GITHUB_WORKSPACE}/.github/workflows/test_es.sh"
