name: Test script

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - run: echo "------------"
      - uses: actions/test@master
      - run: echo "------------"
